-- Add full participant-detail fields (surname, TFF ID, gender, DOB, NIC,
-- religion, school info, TFF email, address) from the founder's participant
-- records spreadsheet, and bring in every participant who has ever enrolled
-- (not just the 45 currently active), including the one who left the
-- programme after passing away and everyone who left along the way.

alter table participants
  add column surname text,
  add column tff_id text,
  add column gender text,
  add column tff_email text,
  add column address text,
  add column religion text,
  add column date_of_birth date,
  add column nic text,
  add column school text,
  add column medium text,
  add column qualification text;

alter table participants drop constraint if exists participants_status_check;
alter table participants add constraint participants_status_check
  check (status in ('Active', 'On Leave', 'Left', 'Deceased'));

-- Fill in details for the 45 participants already in the portal
update participants set surname = 'Ashokraja', tff_id = 'TFF19', gender = 'Female', tff_email = 'kopina.ashokraja.tff@gmail.com', address = '5 house lane, Navatkuli', contact_phone = '740298272', contact_email = 'kobikakobikakobi1@gmail.com', religion = 'Hindu', date_of_birth = '2004-09-25', nic = '200476901724', school = 'Navatkuli MahaVidyalayam', medium = 'Tamil', qualification = 'A/L' where full_name = 'Kopina';
update participants set surname = 'Esan', tff_id = 'TFF20', gender = 'Female', tff_email = 'koshalya.esan.tff@gmail.com', address = '29, 3rd lane, Arasady road, Nallur, Jaffna', contact_phone = '778421460', contact_email = 'esankoshalya@gmail.com', religion = 'Hindu', date_of_birth = '2006-07-24', nic = '200670602154', school = 'Jaffna Holy Family Convent', medium = 'Tamil', qualification = 'A/L' where full_name = 'Koshalya';
update participants set surname = 'Suthakar', tff_id = 'TFF29', gender = 'Female', tff_email = 'nishany.suthakar.tff@gmail.com', address = 'Avvaththai Karanavai West Karaveddy', contact_phone = '768706720', contact_email = null, religion = 'Hindu', date_of_birth = '2006-10-25', nic = '200679901384', school = 'Vadamarachchy Ladies College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Nishany';
update participants set surname = 'Pushparajah', tff_id = 'TFF35', gender = 'Female', tff_email = 'prashayini.pushparajah.tff@gmail.com', address = '43/2, Somasundaram Avenue, Jaffna', contact_phone = '753537020', contact_email = 'shayinipushparajah@gmail.com', religion = 'Hindu', date_of_birth = '2002-08-18', nic = '200273100104', school = 'Vembadi Girls'' High School', medium = 'Tamil', qualification = 'A/L' where full_name = 'Prashayini';
update participants set surname = 'Ratnasingam', tff_id = 'TFF36', gender = 'Female', tff_email = 'putanthahi.ratnasingam.tff@gmail.com', address = 'Chankanai East, Pandatharippu.', contact_phone = '771908852', contact_email = 'pururatnam24@gmail.com', religion = 'Hindu', date_of_birth = '2006-11-24', nic = null, school = 'Chundikuli Girls'' College', medium = 'English', qualification = 'A/L' where full_name = 'Putanthahi';
update participants set surname = 'Antony', tff_id = 'TFF39', gender = 'Female', tff_email = 'sabina.antony.tff@gmail.com', address = '4, Central West Road, Gurunagar, Jaffna', contact_phone = '772395928', contact_email = 'samirthan2002@gmail.com', religion = 'Christian', date_of_birth = '2006-11-03', nic = '200680802558', school = null, medium = 'Tamil', qualification = 'O/L' where full_name = 'Sabina';
update participants set surname = 'Sivapalan', tff_id = 'TFF40', gender = 'Female', tff_email = 'sivapalan.sahana.tff@gmail.com', address = '74/67 Pillayar Kovil Road, Nedunkulam, Jaffna', contact_phone = '779697472', contact_email = 'sahanasivapalan2006@gmail.com', religion = 'Hindu', date_of_birth = '2006-03-27', nic = '200658702264', school = 'Jaffna Holy Family Convent', medium = 'Tamil', qualification = 'A/L' where full_name = 'Sahana';
update participants set surname = 'Kumarasamy', tff_id = 'TFF44', gender = 'Male', tff_email = 'sathursan.kumarasamy.tff@gmail.com', address = 'Pakuththarivakam lane, Arasady Amman Road, Thirunelvely', contact_phone = '740015074', contact_email = 'sathursansathursan02@gmail.com', religion = 'Hindu', date_of_birth = '2004-11-02', nic = '200430701780', school = 'Jaffna Stanley College', medium = 'Tamil', qualification = 'O/L' where full_name = 'Sathurshan';
update participants set surname = 'Nagarajan', tff_id = 'TFF48', gender = 'Female', tff_email = 'sukanja.nagarajan.tff@gmail.com', address = 'Kerathivu Road, Navatkuli, Kaithady', contact_phone = '771170983', contact_email = 'sukasukanja73@gmail.com', religion = 'Hindu', date_of_birth = '2007-08-02', nic = '200771500698', school = 'Chundikuli Girls'' College', medium = 'Tamil', qualification = 'O/L' where full_name = 'Sukanja';
update participants set surname = 'Thevalinkam', tff_id = 'TFF51', gender = 'Male', tff_email = 'thanushiyan.thevalinkam.tff@gmail.com', address = '365 Uthayanagar East, Killinochchi', contact_phone = '763588636', contact_email = 'thanusiyan200203@gmail.com', religion = 'Hindu', date_of_birth = '2002-03-31', nic = '200209102397', school = 'Killinochchi Central College', medium = 'Tamil', qualification = 'O/L' where full_name = 'Thanushiyan';
update participants set surname = 'Uthayachchandran', tff_id = 'TFF54', gender = 'Male', tff_email = 'thilakshan.uthayachchandran.tff@gmail.com', address = '18/1 Sivagurunathar veethy, Neeraviyadi, Jaffna', contact_phone = '763770604', contact_email = 'uthayachchandranthilakshan@gmail.com', religion = 'Hindu', date_of_birth = '2005-03-25', nic = '200508501112', school = 'Jaffna Kokuvil Hindu College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Thilakshan';
update participants set surname = 'Subramaniyam', tff_id = 'TFF05', gender = 'Female', tff_email = 'alansiya.subramaniyam.tff@gmail.com', address = 'Murippu Kumara puram Mulliyavalai', contact_phone = '774882775, 0763997183', contact_email = 'anlcanlc138@gmail.com', religion = 'Christian', date_of_birth = '2006-02-19', nic = '200655000111', school = 'Chundikuli Girls'' College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Alansiya';
update participants set surname = 'Rejes Anurakumar', tff_id = 'TFF07', gender = 'Female', tff_email = 'anojini.rejesanurakumar.tff@gmail.com', address = '98, Old park road, Jaffna', contact_phone = '773351625', contact_email = 'sandiyakumari810@gmail.com', religion = 'Christian', date_of_birth = '2006-12-21', nic = '200685600280', school = 'Chundikuli Girls'' College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Anojini';
update participants set surname = 'Kanakesvaran', tff_id = 'TFF10', gender = 'Female', tff_email = 'jishaka.kanagesvaran.tff@gmail.com', address = 'Kaithady East', contact_phone = '762261997', contact_email = 'jeyamalarmalar@gmail.com', religion = 'Hindu', date_of_birth = '2006-12-19', nic = '200685401110', school = 'Chavakachcheri Hindu College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Jishaka';
update participants set surname = 'Thayagnanam', tff_id = 'TFF14', gender = 'Female', tff_email = 'kamsayini.thayagnanam.tff@gmail.com', address = 'Mandan ettam, Karanavai West, Karaveddy', contact_phone = '768120263', contact_email = 'kamsithaya19@gmail.com', religion = 'Hindu', date_of_birth = '2002-09-19', nic = '200276300524', school = 'Nelliady Central College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Kamsayini';
update participants set surname = 'Vijayakaran', tff_id = 'TFF15', gender = 'Male', tff_email = 'karthikan.vijayakaran.tff@gmail.com', address = '10, Fietcher''s Lane, Chundikuli, Jaffna', contact_phone = '724131517', contact_email = 'kankarthi19@gmail.com', religion = 'Christian', date_of_birth = '2004-09-08', nic = '200425201880', school = null, medium = 'Tamil', qualification = null where full_name = 'Karthikan';
update participants set surname = 'Sureshkumar', tff_id = 'TFF17', gender = 'Male', tff_email = 'kishalan.sureshkumar.tff@gmail.com', address = 'Kaithady West, Kaithady', contact_phone = '761720091', contact_email = 'sureshkumarkishalan@gmail.com', religion = 'Hindu', date_of_birth = '2003-03-14', nic = '200307410252', school = 'Chavakachcheri Hindu College', medium = 'Tamil', qualification = 'O/L, Dip Eng, Dip BM, Dip IT' where full_name = 'Kishalan';
update participants set surname = 'Lingeswaran', tff_id = 'TFF21', gender = 'Male', tff_email = 'lapishanth.lingeswaran.tff@gmail.com', address = 'Old Post Office Road, Kopay South, Kopay', contact_phone = '774941266', contact_email = null, religion = 'Hindu', date_of_birth = '2006-11-06', nic = '200631100537', school = 'Jaffna Central College', medium = 'Tamil', qualification = null where full_name = 'Lapishanth';
update participants set surname = 'Ranjithkumar', tff_id = 'TFF24', gender = 'Female', tff_email = 'mathusika.ranjithkumar.tff@gmail.com', address = 'Kaithady West, Kaithady', contact_phone = '751560722', contact_email = 'rruniththa@gmail.com', religion = 'Hindu', date_of_birth = '2006-03-04', nic = '200656401238', school = 'Chavakachcheri Hindu College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Mathusika';
update participants set surname = 'Sahayaseelan', tff_id = 'TFF50', gender = 'Female', tff_email = 'thamiliny.sahayaseelan.tff@gmail.com', address = 'Point Pedro road, Sinneruvan lane', contact_phone = '750854502', contact_email = 'thamilthamil942@gmail.com', religion = 'Christian', date_of_birth = '2001-12-22', nic = null, school = 'O.L.R school', medium = 'Tamil', qualification = 'O/L' where full_name = 'Tamilini';
update participants set surname = 'Subramaniyam', tff_id = 'TFF52', gender = null, tff_email = 'thanusu.subramaniyam.tff@gmail.com', address = null, contact_phone = '702158610', contact_email = 'thanuthanush578@gmail.com', religion = 'Christian', date_of_birth = '2006-10-07', nic = '200619200051', school = 'Jaffna St.John''s College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Thanusu';
update participants set surname = 'Bakeekaran', tff_id = 'TFF53', gender = 'Female', tff_email = 'tharanginy.bakeekaran.tff@gmail.com', address = 'Urumpirai West, Annungai', contact_phone = '742254805', contact_email = 'anubakee@gmail.com', religion = 'Hindu', date_of_birth = '2006-11-24', nic = null, school = 'Jaffna Kokuvil Hindu College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Tharanginy';
update participants set surname = 'Sunthar', tff_id = 'TFF01', gender = 'Female', tff_email = 'sunthar.abarna.tff@gmail.com', address = '370/2 Semoney road, Nayanmarkadu Jaffna', contact_phone = '778605105', contact_email = 'abarnaonlinework@gmail.com', religion = 'Christian', date_of_birth = '2006-05-26', nic = '200664702448', school = 'Jaffna Holy Family Convent', medium = 'Tamil', qualification = 'A/L' where full_name = 'Abarna';
update participants set surname = 'Nishanthan', tff_id = 'TFF03', gender = 'Male', tff_email = 'akxshayan.nishanthan.tff@gmail.com', address = '268 Pallaly Road, Kantharmadam, Jaffna', contact_phone = '743903941', contact_email = null, religion = 'Hindu', date_of_birth = '2009-01-13', nic = '200901300019', school = 'J/Senkuntha Hindu College', medium = 'Tamil', qualification = 'O/L' where full_name = 'Akshayan';
update participants set surname = 'Thirunesan', tff_id = 'TFF08', gender = 'Female', tff_email = 'banusha.thirunesan.tff@gmail.com', address = 'No. 61, 4th Cross street, Columbuthurai, Jaffna', contact_phone = '772312379', contact_email = null, religion = 'Hindu', date_of_birth = '2006-03-17', nic = '200657700518', school = 'Chundikuli Girls'' College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Banusha';
update participants set surname = 'Karunakaran', tff_id = 'TFF16', gender = 'Male', tff_email = 'kathirshan.karunakaran.tff@gmail.com', address = 'Amman Road, Thirunelvely, Jaffna', contact_phone = '769236317', contact_email = 'kathirkathirshan4@gmail.com', religion = 'Hindu', date_of_birth = '2006-05-28', nic = '200614901142', school = 'Jaffna Hindu College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Kathirshan';
update participants set surname = 'Donald', tff_id = 'TFF25', gender = 'Female', tff_email = 'nilakshana.donald.tff@gmail.com', address = '67/2, Groussault Road, Chundikuli, Jaffna', contact_phone = '778940796', contact_email = 'nilakshana186@gmail.com', religion = 'Christian', date_of_birth = '2004-07-27', nic = '200470900160', school = 'Chundikuli Girls'' College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Nilakshana';
update participants set surname = 'Theiventhiram', tff_id = 'TFF31', gender = 'Female', tff_email = 'parustana.theiventhiram.tff@gmail.com', address = 'Kaithady North, Kaithady', contact_phone = '0767325628, 0743573986', contact_email = 'sarujansaru633@gmail.com', religion = 'Hindu', date_of_birth = '2006-03-23', nic = '200658300146', school = 'Jaffna Hindu Ladies College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Parustana';
update participants set surname = 'Yogarasa', tff_id = 'TFF32', gender = 'Male', tff_email = 'pirasanna.yogaraja.tff@gmail.com', address = 'Sebastian road, Mathagal, Jaffna', contact_phone = '772673012', contact_email = 'vithushananantharayar@gmail.com', religion = 'Christian', date_of_birth = '2009-04-09', nic = '200910003134', school = 'St. Charles Mahavithiyalayam', medium = 'Tamil', qualification = null where full_name = 'Pirasanna';
update participants set surname = 'Sivakumar', tff_id = 'TFF37', gender = 'Female', tff_email = 'raksayana.sivakumar.tff@gmail.com', address = 'Mandan ettam, Karanavai East, Karaveddy', contact_phone = '771725680', contact_email = 'selvarasathayalini@gmail.com', religion = 'Hindu', date_of_birth = '2006-06-08', nic = '200666001523', school = 'Vadamarachchy Ladies College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Raksayana';
update participants set surname = 'Thanaraj', tff_id = 'TFF43', gender = 'Female', tff_email = 'sathana.thanaraj.tff@gmail.com', address = 'Muthalaikkuli Karanavai South, Karaveddy', contact_phone = '763231626', contact_email = 'sathanasathu44@gmail.com', religion = 'Hindu', date_of_birth = '2006-02-04', nic = '200653500942', school = 'Vadamarachchy Ladies College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Sathana';
update participants set surname = 'Kulenthiran', tff_id = 'TFF45', gender = 'Female', tff_email = 'sharony.kulenthiran.tff@gmail.com', address = 'New housing scheme Navatkuly West', contact_phone = '773268141', contact_email = 'jesussharony@gmail.com', religion = 'Christian', date_of_birth = '2005-09-27', nic = '200577102452', school = 'Navatkuli MahaVidyalayam', medium = 'Tamil', qualification = 'A/L' where full_name = 'Sharony';
update participants set surname = 'Theiventhiran', tff_id = 'TFF47', gender = 'Female', tff_email = 'sujanki.theiventhiran.tff@gmail.com', address = 'Kaithady South, Kaithady', contact_phone = '763146808', contact_email = null, religion = 'Hindu', date_of_birth = '2006-10-08', nic = '200678201071', school = 'Chavakachcheri Hindu College', medium = 'Tamil', qualification = 'A/L, Certificate in IT' where full_name = 'Sujanki';
update participants set surname = 'Panjalingham', tff_id = 'TFF49', gender = 'Female', tff_email = 'thadshayini.panjalingam.tff@gmail.com', address = '42/3, Vidhanes road, Chundikuli', contact_phone = '765943427', contact_email = null, religion = 'Hindu', date_of_birth = '2007-04-29', nic = null, school = 'Jaffna Holy Family Convent', medium = 'Tamil', qualification = 'O/L' where full_name = 'Thadsayini';
update participants set surname = 'Sivachelvam', tff_id = 'TFF55', gender = 'Female', tff_email = 'thiviya.sivachelvam.tff@gmail.com', address = '186/12 Kurunathar Suwamy lane, Point petro road, Jaffna', contact_phone = '741636931', contact_email = 'sivachelvamthiviya@gmail.com', religion = 'Hindu', date_of_birth = '2006-11-02', nic = '200680702650', school = 'Jaffna Holy Family Convent', medium = 'Tamil', qualification = 'A/L' where full_name = 'Thiviya';
update participants set surname = 'Sivanesan', tff_id = 'TFF02', gender = 'Female', tff_email = 'acksaya.sivanesan.tff@gmail.com', address = 'Periyavilan, Ilavalai', contact_phone = '741112827', contact_email = 'acksayasivanesan@gmail.com', religion = 'Hindu', date_of_birth = '2006-10-24', nic = '200679800110', school = 'Jaffna Pandateruppu Girl''s high school', medium = 'Tamil', qualification = 'A/L' where full_name = 'Acksaya';
update participants set surname = 'Sahayaseelan', tff_id = 'TFF09', gender = 'Female', tff_email = 'hanoji.sahayaseelan.tff@gmail.com', address = 'Kodikamam Point Pedro Road, Sinneruvan lane', contact_phone = '760453577', contact_email = null, religion = 'Christian', date_of_birth = '2005-01-25', nic = '200552503132', school = 'Our Lady of Refuge', medium = 'Tamil', qualification = 'O/L' where full_name = 'Hanoji';
update participants set surname = 'Vimal Raj', tff_id = 'TFF11', gender = 'Male', tff_email = 'judevinistan.vimalraj.tff@gmail.com', address = 'No. 75, 3rd Cross street, Maniyanthoddam, Jaffna', contact_phone = '770783422', contact_email = 'judevinistan.123@gmail.com', religion = 'Christian', date_of_birth = '2005-12-19', nic = '200535400509', school = 'Jaffna St.John''s College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Jude Vinistan';
update participants set surname = 'Sivakumar', tff_id = 'TFF12', gender = 'Female', tff_email = 'juliyajoy.sivakumar.tff@gmail.com', address = 'Living Light Mission, Massiyapitti Sandilipay', contact_phone = '752264202', contact_email = 'juliyajoy17@icloud.com', religion = 'Christian', date_of_birth = '2005-09-17', nic = '200576100838', school = 'Jaffna Skandavarodhaya College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Juliya Joy';
update participants set surname = 'Selvarasa', tff_id = 'TFF13', gender = 'Female', tff_email = 'kalaikshana.selvarasa.tff@gmail.com', address = 'Navetkuli East, Thachchanthoppu.', contact_phone = '774819534', contact_email = 'kalaikshanakalaikshana@gmail.com', religion = 'Hindu', date_of_birth = '2004-10-06', nic = '200478001368', school = 'Chavakachcheri Hindu College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Kalaikshana';
update participants set surname = 'Prabakaran', tff_id = 'TFF18', gender = 'Female', tff_email = 'kishani.prabakaran.tff@gmail.com', address = 'Vijayakiri, School lane, Navatkuli, Kaithady', contact_phone = '743052800', contact_email = 'kishapraba111@gmail.com', religion = 'Hindu', date_of_birth = '2005-06-24', nic = '200567600607', school = 'Chundikuli Girls'' College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Kishani';
update participants set surname = 'Pathmanathan', tff_id = 'TFF22', gender = 'Female', tff_email = 'mathusha.pathmanathan.tff@gmail.com', address = 'Innuvil Road, 1st Cross, Manipay', contact_phone = '743151345', contact_email = 'mathurich1@gmail.com', religion = 'Hindu', date_of_birth = '2003-10-21', nic = '200379500098', school = 'Manipay Memorial English School', medium = 'Tamil', qualification = 'O/L' where full_name = 'Mathusha.P';
update participants set surname = 'Subakaran', tff_id = 'TFF33', gender = 'Male', tff_email = 's.piraveen.tff@gmail.com', address = '18/10, Ampal Veethy, Nayanmarkaddu, Jaffna', contact_phone = '777562398', contact_email = 'kingytf7@gmail.com', religion = 'Hindu', date_of_birth = '2004-06-24', nic = '200417601500', school = 'Stanley College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Piraveen';
update participants set surname = 'Thirunavukkarasu', tff_id = 'TFF34', gender = 'Female', tff_email = 'pirisa.thirunaa.tff@gmail.com', address = 'Cenaiyoor Mavadichchenai', contact_phone = '772639264', contact_email = 'piru2006@gmail.com', religion = 'Hindu', date_of_birth = '2006-06-11', nic = '200666303000', school = 'Mavadichchenai', medium = 'Tamil', qualification = 'A/L' where full_name = 'Pirisa';
update participants set surname = 'Kugathas', tff_id = 'TFF46', gender = 'Male', tff_email = 'sivaruban.kugathas.tff@gmail.com', address = 'Market lane Imayanan West, Uduppiddy', contact_phone = '771375383', contact_email = 'skrooban2803@gmail.com', religion = 'Hindu', date_of_birth = '2006-12-28', nic = '200636300743', school = 'Udduppiddy American Mission College', medium = 'Tamil', qualification = 'A/L' where full_name = 'Sivaruban';

-- Everyone else who has ever enrolled (mostly people who left before
-- Phase 3, plus the one participant who passed away)
insert into participants
  (full_name, family_id, joining_date, status, surname, gender, tff_email, address,
   contact_phone, contact_email, religion, date_of_birth, nic, school, medium, qualification)
values
  ('Abisha', (select id from families where name = 'Arising Brilliance'), '2026-02-23', 'Left', 'Kanagarasa', 'Female', null, 'Ward No. 03 Velanai East Velanai', '778547984', 'abishakanagarasa@gmail.com', 'Hindu', '2006-05-04', '200662502421', 'Jaffna Holy Family Convent', 'Tamil', 'A/L'),
  ('Akash', (select id from families where name = 'Benevolent'), '2026-02-23', 'Left', 'Krishnapalan', 'Male', 'akash.krishnapalan.tff@gmail.com', 'Koiyathoddam 1st lane, Irupalai East, Irupalai Kopay', '743210148', 'akashkrishnapalan529@gmail.com', 'Christian', '2005-08-26', '200523900350', 'Jaffna St.John''s College', 'Tamil', 'A/L'),
  ('Ann Ilakkiya', null, '2026-02-23', 'Left', 'Navasothy', 'Female', null, '288, Bankshall street, Gurunagar, Jaffna', '766694753', 'annilakkiya@gmail.com', 'Christian', '2006-08-19', '200673200374', 'Chundikuli Girls'' College', 'Tamil', 'A/L'),
  ('Ann Mareena', (select id from families where name = 'Believers'), '2026-02-23', 'Active', 'Mohanraj', 'Female', 'annmareena.mohanraj.tff@gmail.com', 'Alukkai, Alaveddy East, Alaveddy', '764182698', 'mohanrajannmareena@gmail.com', 'Christian', '2005-11-21', '200582603473', 'Jaffna Arunodaya College', 'Tamil', 'A/L'),
  ('Bathusanan', null, '2026-02-23', 'Left', 'Srikularaja', 'Male', null, 'Muthaliyar Valavu K.K.S road, Chunnakam', '779989164', 'sbathu14@gmail.com', 'Hindu', '2001-01-14', '200101402429', 'Jaffna Union College', 'Tamil', 'B.A (Hons)'),
  ('Bavatharani', null, '2026-02-23', 'Left', 'Theiventhiram', 'Female', null, 'Alvai, South, Alvai', '760315049', 'tharaniyanchitharu@gmail.com', 'Hindu', '2006-10-27', '200680101065', 'Vadamarachchy Ladies College', 'Tamil', 'A/L'),
  ('Jathurshan', null, '2026-03-16', 'Left', 'Thirugnana Sampanthamoorthy', 'Male', null, '25, Kaladdy Lane Kondavil West Kondavil', '776317109', 'jathurshanrt@gmail.com', 'Hindu', '2006-10-01', '200627500966', 'Jaffna Kokuvil Hindu College', 'Tamil', 'A/L'),
  ('Jathusha', null, '2026-02-23', 'Left', 'Selvaraththinam', 'Female', null, 'Kathaidy North Kathaidy', '741859139', null, 'Hindu', '2006-01-22', null, 'Chavakachcheri Hindu College', 'Tamil', 'A/L'),
  ('Kajan', null, '2026-03-12', 'Left', 'Raveenthiran', 'Male', null, 'Kaithady Central Kaithady', '773114260', 'kanir7580@gmail.com', 'Hindu', '2006-09-17', '200626100820', 'Kaithady Vigneshwara Vidyalayam', 'Tamil', 'O/L'),
  ('Kajeevana', (select id from families where name = 'Loving'), '2026-03-17', 'Left', 'Puvanenthiran', 'Female', null, 'Velanai West Wo. No - 6', '768984592', null, 'Hindu', '2006-05-01', '200662200864', 'Velanai Central College', 'Tamil', 'A/L'),
  ('Karishini', (select id from families where name = 'Arising Brilliance'), '2026-02-23', 'Left', 'Suresh', 'Female', null, 'School lane, Navatkuli, Kaithady', '769115819', 'katrishinisuresh29@gmail.com', 'Hindu', '2006-05-29', '200665000387', 'Chundikuli Girls'' College', 'Tamil', 'A/L'),
  ('Kaveena', (select id from families where name = 'Loving'), '2026-03-12', 'Left', 'Sivabalasuntharam', 'Female', null, '80/25, Pirampady lane, Kokuvil East, Kokuvil', '775296417', 'sivakavee1471@gmail.com', 'Hindu', '2006-03-10', '200657001192', 'Vembadi Girls'' High School', 'Tamil', 'A/L'),
  ('Kujinsika', null, '2026-02-23', 'Left', 'Vijayakumar', 'Female', null, 'Velanai East Velanai: 04 Ward', '770213180', null, 'Hindu', '2006-04-21', '200661202781', 'Velanai Central College', 'Tamil', 'A/L'),
  ('Malavika', (select id from families where name = 'Benevolent'), '2026-02-23', 'Left', 'Ariyaratnam', 'Female', null, 'Ampanai, Chunnakam West, Chunnakam', '740379726', 'malavikaariyaratnam@gmail.com', 'Hindu', '2005-07-07', '200568901132', 'Uduvil Girls'' College', 'Tamil', 'A/L'),
  ('Mathusha.S', (select id from families where name = 'Believers'), '2026-02-23', 'Left', 'Selvarasa', 'Female', 'mathusha.selvarasa.tff@gmail.com', 'Navatkuli East, Thachchan Thoppu', '771808960', 'mathushmathu137@gmail.com', 'Hindu', '2004-10-05', '200477901770', 'Jaffna Holy Family Convent', 'Tamil', 'A/L'),
  ('Nilany', (select id from families where name = 'Loving'), '2026-02-23', 'Left', 'Uthayakumar', 'Female', 'nilany.uthakumar.tff@gmail.com', 'Mugamalai North, Pallai', '764753183', 'nilanilan091@gmail.com', 'Hindu', '2006-03-07', '200656701420', 'Pallai Central College', 'Tamil', 'A/L'),
  ('Nirogithan', (select id from families where name = 'Loving'), '2026-03-17', 'Left', 'Sivakumar', 'Male', null, 'Valliavaththai, Karanavai West, Karaveddy', '768850238', 'sivakumarnirogithan@gmail.com', 'Hindu', '2006-08-31', '200624400649', 'Udduppiddy American Mission College', 'Tamil', 'A/L'),
  ('Niruthigan', (select id from families where name = 'Arising Brilliance'), '2026-04-23', 'Deceased', 'Mahadeva Uthayakumar', 'Male', null, '237/7, Puwaneswary anbal Road, Ariyalai West, Jaffna', '706510285', 'uthayakumarniruthigan@gmail.com', 'Hindu', '2006-10-29', '200630300860', 'Jaffna St.John''s College', 'English', 'A/L'),
  ('Nithushana', (select id from families where name = 'Arising Brilliance'), '2026-02-23', 'Left', 'Sureshkumar', 'Female', null, 'N0. 50 Ariyalai Poompugar East, Jaffna', '773593513', 'malarsures117@gmail.com', 'Hindu', '2026-02-23', '200660800337', 'Jaffna Holy Family Convent', 'Tamil', 'A/L'),
  ('Piraveena', null, '2026-02-23', 'Left', 'Sowntharaja', 'Female', null, 'Keratheve Road, Navatkuli, Kaithady', '770651327', 'piraveenasowntharaja@gmail.com', 'Hindu', '2006-06-08', '200666001493', 'Navatkuli MahaVidyalayam', 'Tamil', 'A/L'),
  ('Robini', (select id from families where name = 'Loving'), '2026-03-16', 'Left', 'Srikanthan', 'Female', null, '244 1/45 2nd lane Thetkiluppai kulam, Vavuniya', '776098108', 'thiverich@gmail.com', 'Christian', '2001-05-31', '200165201588', 'Vavuniya Hindu College', 'Tamil', 'A/L'),
  ('Sachin Kanabathi', null, '2026-02-27', 'Left', 'Anderson', 'Male', null, '3/3 Adappan Road, Jaffna', '713535216', 'sachinnilaks@gmail.com', 'Christian', '2005-06-10', '200516200483', 'Jaffna St.John''s College', 'Tamil', 'A/L'),
  ('Samsan', (select id from families where name = 'Arising Brilliance'), '2026-02-23', 'Left', 'Theventhirarasa', 'Male', null, 'Velanai West Velanai, Ambigaingr Wo - 08', '768776182', 'samsan200411@gmail.com', 'Hindu', '2004-11-12', '200431701211', 'Velanai Central College', 'Tamil', 'A/L'),
  ('Sankeerththanan', (select id from families where name = 'Believers'), '2026-02-23', 'Left', 'Sasikaran', 'Male', 'sankeerththanan.sasikaran.tff@gmail.com', 'No.67, Solai, Pallavarayankaddu', '778914486', 'sankeerththanan12@gmail.com', 'Hindu', '2006-12-26', '200636100580', 'Killinochchi Mulankavil Mahavidyalam', 'Tamil', 'A/L'),
  ('Shallomy', (select id from families where name = 'Loving'), '2026-02-23', 'Left', 'Rajakanistan', 'Female', null, '82/10, Yarl Road, Jafna', '772417872', 'rajakanistankeetha@gmail.com', 'Christian', '2007-06-09', '197766903561', 'Jaffna Hindu Ladies College', 'Tamil', 'O/L'),
  ('Shampavi', (select id from families where name = 'Believers'), '2026-02-23', 'Left', 'Sathies', 'Female', null, '"Theiva nilal",Malvam,uduvil,chunnakam', '760368212', 'sathiesshampavi@gmail.com', 'Hindu', '2005-10-02', '200577600678', 'Uduvil Girls'' College', 'Tamil', 'A/L'),
  ('Srithuvaraka', null, '2026-02-23', 'Left', 'Ratnakumar', 'Female', null, 'No. 25, Eachchamoddai Road, Jaffna', '770278865', null, 'Hindu', '2000-09-14', '200075801535', 'Chundikuli Girls'' College', 'Tamil', 'Degree (B.A (Hons) Political Science'),
  ('Suvarnuga', null, '2026-03-03', 'Left', 'Mayoorathan', 'Female', null, 'Moolao 2nd lane, Vaddu South, Vaddukoddai', '778365212', 'thulashansuvarnuga', 'Hindu', '2006-05-21', '200664200898', 'Jaffna College', 'Tamil', 'O/L'),
  ('Thanusiya', null, '2026-02-23', 'Left', 'Vickneswaran', 'Female', null, 'Muthalaikkuli Karanavai South, Karaveddy', '750621696', 'tharanithanu912@gmail.com', 'Hindu', '2006-12-15', '200685001020', 'Vadamarachchy Ladies College', 'Tamil', 'A/L'),
  ('Thiviha', (select id from families where name = 'Loving'), '2026-02-23', 'Left', 'Kajenthirakumar', 'Female', null, 'Velanai East Velanai: 03 Ward', '771434114', 'thivihathivik36@gmail.com', 'Hindu', '2006-08-03', '200671602434', 'Velanai Central College', 'Tamil', 'A/L'),
  ('Thushana', null, '2026-03-03', 'Left', 'Uthaya Sooriyan', 'Female', null, 'Nallamavady road, Vaddu South, Vaddukoddai', '742720753', null, 'Hindu', '2007-01-08', '200750800854', 'Jaffna College', 'Tamil', 'A/L'),
  ('Vithusha', (select id from families where name = 'Believers'), '2026-02-23', 'Left', 'Jeevananthan', 'Female', null, 'Velanai West Velanai - 06', '772914177', 'vithusha432@gmail.com', 'Hindu', '2006-10-06', '200678000902', 'Velanai Central College', 'Tamil', 'A/L'),
  ('Vishnusaran', (select id from families where name = 'Arising Brilliance'), '2026-03-17', 'Left', 'Mathanakumar', 'Male', null, '29, Kalasalai Road, Thirunelvely, Jaffna', '774201758', 'vishnusaran199@gmail.com', 'Hindu', '2009-10-09', '200928304064', 'Jaffna Central College', 'Tamil', 'O/L'),
  ('Nithushana (Sivananthan)', null, '2026-03-26', 'Left', 'Sivananthan', 'Male', null, 'Kumarakoddam, Kondavil', '774025079', 'sivananthannithusan@gmail.com', 'Hindu', '2006-11-16', '200632101406', 'Jaffna Kokuvil Hindu College', 'Tamil', 'A/L');
