-- Historical scores from the 2026_SEPTEMBER assessment sheet.
-- The raw values below are recovered directly from the sheet's own
-- component columns (Flu Avg, Conf /100 inverted back to a 1-6 raw score,
-- Speaking/Writing/Listening/Reading/Grammar, Assessment Score, Fluency Avg,
-- Conf Score) - matched to participants by name. A handful of absent/blank
-- cells in the sheet are simply left unscored here, same as any partially
-- entered assessment in the app.

insert into assessment_scores (phase_id, participant_id)
select (select id from assessment_phases where name = '① IEP Baseline'), p.id
from participants p
where p.full_name in (
    'Abarna',
    'Acksaya',
    'Akshayan',
    'Alansiya',
    'Ann Mareena',
    'Anojini',
    'Banusha',
    'Hanoji',
    'Jishaka',
    'Jude Vinistan',
    'Juliya Joy',
    'Kalaikshana',
    'Kamsayini',
    'Karthikan',
    'Kathirshan',
    'Kishalan',
    'Kishani',
    'Kopina',
    'Koshalya',
    'Lapishanth',
    'Mathusha.P',
    'Mathusha.S',
    'Mathusika',
    'Nilakshana',
    'Nilany',
    'Nirogithan',
    'Niruthigan',
    'Nishany',
    'Nithushana',
    'Parustana',
    'Pirasanna',
    'Piraveen',
    'Pirisa',
    'Prashayini',
    'Putanthahi',
    'Raksayana',
    'Robini',
    'Sabina',
    'Sahana',
    'Samsan',
    'Sankeerththanan',
    'Sathana',
    'Sathurshan',
    'Sharony',
    'Sivaruban',
    'Sujanki',
    'Sukanja',
    'Tamilini',
    'Thadsayini',
    'Thanushiyan',
    'Thanusu',
    'Tharanginy',
    'Thilakshan',
    'Thiviya'
)
on conflict (phase_id, participant_id) do nothing;

insert into assessment_scores (phase_id, participant_id)
select (select id from assessment_phases where name = '② Phase 1'), p.id
from participants p
where p.full_name in (
    'Abarna',
    'Acksaya',
    'Akash',
    'Akshayan',
    'Alansiya',
    'Ann Mareena',
    'Anojini',
    'Banusha',
    'Hanoji',
    'Jishaka',
    'Jude Vinistan',
    'Juliya Joy',
    'Kalaikshana',
    'Kamsayini',
    'Karthikan',
    'Kathirshan',
    'Kishalan',
    'Kishani',
    'Kopina',
    'Koshalya',
    'Lapishanth',
    'Mathusha.P',
    'Mathusha.S',
    'Mathusika',
    'Nilakshana',
    'Nilany',
    'Nirogithan',
    'Niruthigan',
    'Nishany',
    'Nithushana',
    'Parustana',
    'Pirasanna',
    'Piraveen',
    'Pirisa',
    'Prashayini',
    'Putanthahi',
    'Raksayana',
    'Robini',
    'Sabina',
    'Sahana',
    'Samsan',
    'Sankeerththanan',
    'Sathana',
    'Sathurshan',
    'Sharony',
    'Sivaruban',
    'Sujanki',
    'Sukanja',
    'Tamilini',
    'Thadsayini',
    'Thanushiyan',
    'Thanusu',
    'Tharanginy',
    'Thilakshan',
    'Thiviya',
    'Vishnusaran'
)
on conflict (phase_id, participant_id) do nothing;

insert into assessment_scores (phase_id, participant_id)
select (select id from assessment_phases where name = '③ Umbrella Problem'), p.id
from participants p
where p.full_name in (
    'Abarna',
    'Acksaya',
    'Akshayan',
    'Alansiya',
    'Ann Mareena',
    'Anojini',
    'Banusha',
    'Hanoji',
    'Jishaka',
    'Jude Vinistan',
    'Juliya Joy',
    'Kalaikshana',
    'Kamsayini',
    'Karthikan',
    'Kathirshan',
    'Kishalan',
    'Kishani',
    'Kopina',
    'Koshalya',
    'Lapishanth',
    'Mathusha.P',
    'Mathusika',
    'Nilakshana',
    'Niruthigan',
    'Nishany',
    'Parustana',
    'Pirasanna',
    'Piraveen',
    'Pirisa',
    'Prashayini',
    'Putanthahi',
    'Raksayana',
    'Sabina',
    'Sahana',
    'Sathana',
    'Sathurshan',
    'Sharony',
    'Sivaruban',
    'Sujanki',
    'Sukanja',
    'Tamilini',
    'Thadsayini',
    'Thanushiyan',
    'Tharanginy',
    'Thilakshan',
    'Thiviya'
)
on conflict (phase_id, participant_id) do nothing;

insert into assessment_scores (phase_id, participant_id)
select (select id from assessment_phases where name = '④ Phase 2'), p.id
from participants p
where p.full_name in (
    'Abarna',
    'Acksaya',
    'Ann Mareena',
    'Anojini',
    'Banusha',
    'Jishaka',
    'Jude Vinistan',
    'Juliya Joy',
    'Kalaikshana',
    'Kamsayini',
    'Karthikan',
    'Kathirshan',
    'Kishalan',
    'Kishani',
    'Kopina',
    'Koshalya',
    'Lapishanth',
    'Mathusha.P',
    'Mathusika',
    'Nilakshana',
    'Niruthigan',
    'Nishany',
    'Parustana',
    'Pirasanna',
    'Piraveen',
    'Pirisa',
    'Prashayini',
    'Putanthahi',
    'Raksayana',
    'Sabina',
    'Sahana',
    'Sathana',
    'Sathurshan',
    'Sharony',
    'Sivaruban',
    'Sujanki',
    'Sukanja',
    'Tamilini',
    'Thadsayini',
    'Thanushiyan',
    'Tharanginy',
    'Thilakshan',
    'Thiviya'
)
on conflict (phase_id, participant_id) do nothing;

insert into assessment_component_scores (assessment_score_id, component_id, raw_value)
select s.id,
  (select id from assessment_components where phase_id = (select id from assessment_phases where name = '① IEP Baseline') and name = 'Fluency'),
  v.val
from assessment_scores s
join participants p on p.id = s.participant_id
join (values
    ('Abarna', 3.1),
    ('Acksaya', 2.8),
    ('Akshayan', 2.2),
    ('Alansiya', 2.8),
    ('Ann Mareena', 3.8),
    ('Anojini', 4.1),
    ('Banusha', 4.5),
    ('Hanoji', 2.3),
    ('Jishaka', 3.2),
    ('Jude Vinistan', 2.8),
    ('Juliya Joy', 3.1),
    ('Kalaikshana', 2.9),
    ('Kamsayini', 2.3),
    ('Karthikan', 1.9),
    ('Kathirshan', 2.6),
    ('Kishalan', 4.2),
    ('Kishani', 3.9),
    ('Kopina', 2.5),
    ('Koshalya', 3.3),
    ('Lapishanth', 2.5),
    ('Mathusha.P', 2.3),
    ('Mathusha.S', 2.1),
    ('Mathusika', 3.0),
    ('Nilakshana', 4.5),
    ('Nilany', 4.1),
    ('Nirogithan', 3.4),
    ('Niruthigan', 4.5),
    ('Nishany', 3.1),
    ('Nithushana', 3.1),
    ('Parustana', 2.8),
    ('Pirasanna', 2.9),
    ('Piraveen', 2.8),
    ('Pirisa', 2.9),
    ('Prashayini', 3.7),
    ('Putanthahi', 4.3),
    ('Raksayana', 2.1),
    ('Robini', 3.3),
    ('Sabina', 1.5),
    ('Sahana', 3.1),
    ('Samsan', 1.9),
    ('Sankeerththanan', 3.8),
    ('Sathana', 2.9),
    ('Sathurshan', 2.3),
    ('Sharony', 2.8),
    ('Sivaruban', 2.5),
    ('Sujanki', 3.5),
    ('Sukanja', 3.0),
    ('Thadsayini', 1.9),
    ('Tamilini', 2.3),
    ('Thanushiyan', 2.2),
    ('Thanusu', 2.2),
    ('Tharanginy', 3.7),
    ('Thilakshan', 2.6),
    ('Thiviya', 3.5)
) as v(pname, val) on v.pname = p.full_name
where s.phase_id = (select id from assessment_phases where name = '① IEP Baseline')
on conflict (assessment_score_id, component_id) do nothing;

insert into assessment_component_scores (assessment_score_id, component_id, raw_value)
select s.id,
  (select id from assessment_components where phase_id = (select id from assessment_phases where name = '① IEP Baseline') and name = 'Confidence'),
  v.val
from assessment_scores s
join participants p on p.id = s.participant_id
join (values
    ('Abarna', 4.33),
    ('Acksaya', 4.67),
    ('Akshayan', 2.67),
    ('Alansiya', 3.33),
    ('Ann Mareena', 5.0),
    ('Anojini', 4.67),
    ('Banusha', 5.33),
    ('Hanoji', 3.0),
    ('Jishaka', 4.0),
    ('Jude Vinistan', 4.0),
    ('Juliya Joy', 3.66),
    ('Kalaikshana', 3.33),
    ('Kamsayini', 2.67),
    ('Karthikan', 2.33),
    ('Kathirshan', 3.66),
    ('Kishalan', 5.67),
    ('Kishani', 5.0),
    ('Kopina', 3.33),
    ('Koshalya', 4.0),
    ('Lapishanth', 3.66),
    ('Mathusha.P', 2.33),
    ('Mathusha.S', 2.67),
    ('Mathusika', 3.66),
    ('Nilakshana', 5.0),
    ('Nilany', 5.33),
    ('Nirogithan', 3.66),
    ('Niruthigan', 5.67),
    ('Nishany', 4.0),
    ('Nithushana', 3.66),
    ('Parustana', 3.66),
    ('Pirasanna', 2.67),
    ('Piraveen', 2.33),
    ('Pirisa', 3.0),
    ('Prashayini', 5.0),
    ('Putanthahi', 5.33),
    ('Raksayana', 3.0),
    ('Robini', 4.67),
    ('Sabina', 1.67),
    ('Sahana', 3.66),
    ('Samsan', 2.67),
    ('Sankeerththanan', 4.33),
    ('Sathana', 3.33),
    ('Sathurshan', 3.33),
    ('Sharony', 4.0),
    ('Sivaruban', 3.33),
    ('Sujanki', 5.0),
    ('Sukanja', 3.0),
    ('Thadsayini', 2.33),
    ('Tamilini', 2.33),
    ('Thanushiyan', 3.0),
    ('Thanusu', 2.67),
    ('Tharanginy', 5.33),
    ('Thilakshan', 3.33),
    ('Thiviya', 5.0)
) as v(pname, val) on v.pname = p.full_name
where s.phase_id = (select id from assessment_phases where name = '① IEP Baseline')
on conflict (assessment_score_id, component_id) do nothing;

insert into assessment_component_scores (assessment_score_id, component_id, raw_value)
select s.id,
  (select id from assessment_components where phase_id = (select id from assessment_phases where name = '② Phase 1') and name = 'Speaking'),
  v.val
from assessment_scores s
join participants p on p.id = s.participant_id
join (values
    ('Abarna', 13.0),
    ('Acksaya', 14.0),
    ('Akshayan', 8.0),
    ('Alansiya', 10.0),
    ('Ann Mareena', 15.0),
    ('Anojini', 14.0),
    ('Banusha', 16.0),
    ('Hanoji', 9.0),
    ('Jishaka', 12.0),
    ('Jude Vinistan', 12.0),
    ('Juliya Joy', 11.0),
    ('Kalaikshana', 10.0),
    ('Kamsayini', 8.0),
    ('Karthikan', 7.0),
    ('Kathirshan', 11.0),
    ('Kishalan', 17.0),
    ('Kishani', 15.0),
    ('Kopina', 10.0),
    ('Koshalya', 12.0),
    ('Lapishanth', 11.0),
    ('Mathusha.P', 7.0),
    ('Mathusha.S', 8.0),
    ('Mathusika', 11.0),
    ('Nilakshana', 15.0),
    ('Nilany', 16.0),
    ('Nirogithan', 11.0),
    ('Niruthigan', 17.0),
    ('Nishany', 12.0),
    ('Nithushana', 11.0),
    ('Parustana', 11.0),
    ('Pirasanna', 8.0),
    ('Piraveen', 7.0),
    ('Pirisa', 9.0),
    ('Prashayini', 15.0),
    ('Putanthahi', 16.0),
    ('Raksayana', 9.0),
    ('Robini', 14.0),
    ('Sabina', 5.0),
    ('Sahana', 11.0),
    ('Samsan', 8.0),
    ('Sankeerththanan', 13.0),
    ('Sathana', 10.0),
    ('Sathurshan', 10.0),
    ('Sharony', 12.0),
    ('Sivaruban', 10.0),
    ('Sujanki', 15.0),
    ('Sukanja', 9.0),
    ('Thadsayini', 7.0),
    ('Tamilini', 7.0),
    ('Thanushiyan', 9.0),
    ('Thanusu', 8.0),
    ('Tharanginy', 16.0),
    ('Thilakshan', 10.0),
    ('Thiviya', 15.0)
) as v(pname, val) on v.pname = p.full_name
where s.phase_id = (select id from assessment_phases where name = '② Phase 1')
on conflict (assessment_score_id, component_id) do nothing;

insert into assessment_component_scores (assessment_score_id, component_id, raw_value)
select s.id,
  (select id from assessment_components where phase_id = (select id from assessment_phases where name = '② Phase 1') and name = 'Writing'),
  v.val
from assessment_scores s
join participants p on p.id = s.participant_id
join (values
    ('Abarna', 4.6),
    ('Acksaya', 6.2),
    ('Akshayan', 3.1),
    ('Akash', 5.5),
    ('Alansiya', 6.0),
    ('Ann Mareena', 7.9),
    ('Anojini', 8.9),
    ('Banusha', 9.8),
    ('Hanoji', 2.4),
    ('Jishaka', 6.7),
    ('Jude Vinistan', 5.8),
    ('Juliya Joy', 6.0),
    ('Kalaikshana', 6.7),
    ('Kamsayini', 6.5),
    ('Karthikan', 3.6),
    ('Kathirshan', 7.4),
    ('Kishalan', 9.8),
    ('Kishani', 9.6),
    ('Kopina', 4.6),
    ('Koshalya', 6.7),
    ('Lapishanth', 6.0),
    ('Mathusha.P', 2.4),
    ('Mathusha.S', 5.2),
    ('Mathusika', 5.5),
    ('Nilakshana', 7.7),
    ('Nilany', 7.2),
    ('Niruthigan', 6.5),
    ('Nishany', 5.0),
    ('Nithushana', 7.2),
    ('Parustana', 6.5),
    ('Pirasanna', 3.4),
    ('Piraveen', 6.5),
    ('Pirisa', 6.0),
    ('Prashayini', 9.4),
    ('Putanthahi', 10.1),
    ('Raksayana', 5.8),
    ('Robini', 6.7),
    ('Sabina', 0.0),
    ('Sahana', 6.7),
    ('Samsan', 2.9),
    ('Sankeerththanan', 7.4),
    ('Sathana', 6.2),
    ('Sathurshan', 4.1),
    ('Sharony', 6.5),
    ('Sivaruban', 6.5),
    ('Sujanki', 7.2),
    ('Sukanja', 4.3),
    ('Thadsayini', 3.6),
    ('Tamilini', 4.8),
    ('Thanushiyan', 2.4),
    ('Thanusu', 4.3),
    ('Tharanginy', 7.9),
    ('Thilakshan', 7.2),
    ('Thiviya', 8.9),
    ('Vishnusaran', 7.2)
) as v(pname, val) on v.pname = p.full_name
where s.phase_id = (select id from assessment_phases where name = '② Phase 1')
on conflict (assessment_score_id, component_id) do nothing;

insert into assessment_component_scores (assessment_score_id, component_id, raw_value)
select s.id,
  (select id from assessment_components where phase_id = (select id from assessment_phases where name = '② Phase 1') and name = 'Listening'),
  v.val
from assessment_scores s
join participants p on p.id = s.participant_id
join (values
    ('Abarna', 8.9),
    ('Acksaya', 10.2),
    ('Akshayan', 6.4),
    ('Akash', 5.1),
    ('Alansiya', 10.2),
    ('Ann Mareena', 9.6),
    ('Anojini', 11.5),
    ('Banusha', 8.9),
    ('Hanoji', 6.4),
    ('Jishaka', 9.6),
    ('Jude Vinistan', 7.0),
    ('Juliya Joy', 7.0),
    ('Kalaikshana', 8.3),
    ('Kamsayini', 6.4),
    ('Karthikan', 7.0),
    ('Kathirshan', 7.0),
    ('Kishalan', 10.2),
    ('Kishani', 14.7),
    ('Kopina', 6.4),
    ('Koshalya', 7.7),
    ('Lapishanth', 3.8),
    ('Mathusha.P', 1.3),
    ('Mathusha.S', 5.1),
    ('Mathusika', 7.0),
    ('Nilakshana', 7.7),
    ('Nilany', 8.9),
    ('Niruthigan', 12.8),
    ('Nishany', 8.3),
    ('Nithushana', 7.7),
    ('Parustana', 7.0),
    ('Pirasanna', 7.0),
    ('Piraveen', 8.9),
    ('Pirisa', 5.1),
    ('Prashayini', 12.8),
    ('Putanthahi', 7.7),
    ('Raksayana', 7.7),
    ('Robini', 6.4),
    ('Sabina', 5.1),
    ('Sahana', 8.9),
    ('Samsan', 5.8),
    ('Sankeerththanan', 9.6),
    ('Sathana', 8.9),
    ('Sathurshan', 6.4),
    ('Sharony', 8.3),
    ('Sivaruban', 6.4),
    ('Sujanki', 8.3),
    ('Sukanja', 3.2),
    ('Thadsayini', 0.0),
    ('Tamilini', 5.1),
    ('Thanushiyan', 5.8),
    ('Thanusu', 1.3),
    ('Tharanginy', 9.6),
    ('Thilakshan', 9.6),
    ('Thiviya', 12.1),
    ('Vishnusaran', 7.7)
) as v(pname, val) on v.pname = p.full_name
where s.phase_id = (select id from assessment_phases where name = '② Phase 1')
on conflict (assessment_score_id, component_id) do nothing;

insert into assessment_component_scores (assessment_score_id, component_id, raw_value)
select s.id,
  (select id from assessment_components where phase_id = (select id from assessment_phases where name = '② Phase 1') and name = 'Reading'),
  v.val
from assessment_scores s
join participants p on p.id = s.participant_id
join (values
    ('Abarna', 15.3),
    ('Acksaya', 18.4),
    ('Akshayan', 14.6),
    ('Akash', 14.6),
    ('Alansiya', 13.0),
    ('Ann Mareena', 16.9),
    ('Anojini', 19.9),
    ('Banusha', 19.9),
    ('Hanoji', 1.5),
    ('Jishaka', 13.0),
    ('Jude Vinistan', 12.3),
    ('Juliya Joy', 20.7),
    ('Kalaikshana', 12.3),
    ('Kamsayini', 10.7),
    ('Karthikan', 11.5),
    ('Kathirshan', 7.7),
    ('Kishalan', 19.2),
    ('Kishani', 15.3),
    ('Kopina', 11.5),
    ('Koshalya', 16.9),
    ('Lapishanth', 16.1),
    ('Mathusha.P', 3.1),
    ('Mathusha.S', 16.9),
    ('Mathusika', 10.7),
    ('Nilakshana', 17.6),
    ('Nilany', 13.8),
    ('Niruthigan', 19.2),
    ('Nishany', 10.7),
    ('Nithushana', 17.6),
    ('Parustana', 14.6),
    ('Pirasanna', 4.6),
    ('Piraveen', 25.3),
    ('Pirisa', 9.2),
    ('Prashayini', 18.4),
    ('Putanthahi', 18.4),
    ('Raksayana', 16.9),
    ('Robini', 14.6),
    ('Sabina', 4.6),
    ('Sahana', 16.9),
    ('Samsan', 13.0),
    ('Sankeerththanan', 19.2),
    ('Sathana', 18.4),
    ('Sathurshan', 7.7),
    ('Sharony', 15.3),
    ('Sivaruban', 15.3),
    ('Sujanki', 18.4),
    ('Sukanja', 12.3),
    ('Thadsayini', 10.7),
    ('Tamilini', 16.1),
    ('Thanushiyan', 10.7),
    ('Tharanginy', 20.7),
    ('Thilakshan', 16.9),
    ('Thiviya', 16.1),
    ('Vishnusaran', 16.1)
) as v(pname, val) on v.pname = p.full_name
where s.phase_id = (select id from assessment_phases where name = '② Phase 1')
on conflict (assessment_score_id, component_id) do nothing;

insert into assessment_component_scores (assessment_score_id, component_id, raw_value)
select s.id,
  (select id from assessment_components where phase_id = (select id from assessment_phases where name = '② Phase 1') and name = 'Grammar'),
  v.val
from assessment_scores s
join participants p on p.id = s.participant_id
join (values
    ('Abarna', 7.2),
    ('Acksaya', 9.9),
    ('Akshayan', 5.4),
    ('Akash', 6.8),
    ('Alansiya', 6.3),
    ('Ann Mareena', 9.0),
    ('Anojini', 8.1),
    ('Banusha', 7.2),
    ('Hanoji', 6.3),
    ('Jishaka', 7.2),
    ('Jude Vinistan', 7.6),
    ('Juliya Joy', 10.8),
    ('Kalaikshana', 15.8),
    ('Kamsayini', 6.3),
    ('Karthikan', 8.5),
    ('Kathirshan', 7.7),
    ('Kishalan', 12.6),
    ('Kishani', 11.2),
    ('Kopina', 6.3),
    ('Koshalya', 5.9),
    ('Lapishanth', 8.1),
    ('Mathusha.P', 5.4),
    ('Mathusha.S', 8.1),
    ('Mathusika', 8.5),
    ('Nilakshana', 9.5),
    ('Nilany', 9.9),
    ('Niruthigan', 10.3),
    ('Nishany', 6.3),
    ('Nithushana', 5.4),
    ('Parustana', 9.0),
    ('Pirasanna', 5.8),
    ('Piraveen', 13.0),
    ('Pirisa', 6.3),
    ('Prashayini', 9.5),
    ('Putanthahi', 9.0),
    ('Raksayana', 5.9),
    ('Robini', 8.5),
    ('Sabina', 5.4),
    ('Sahana', 8.1),
    ('Samsan', 5.4),
    ('Sankeerththanan', 9.9),
    ('Sathana', 9.0),
    ('Sathurshan', 7.2),
    ('Sharony', 7.6),
    ('Sivaruban', 7.2),
    ('Sujanki', 9.0),
    ('Sukanja', 5.4),
    ('Thadsayini', 7.6),
    ('Tamilini', 7.6),
    ('Thanushiyan', 6.8),
    ('Thanusu', 7.2),
    ('Tharanginy', 9.0),
    ('Thilakshan', 13.0),
    ('Thiviya', 9.9),
    ('Vishnusaran', 8.1)
) as v(pname, val) on v.pname = p.full_name
where s.phase_id = (select id from assessment_phases where name = '② Phase 1')
on conflict (assessment_score_id, component_id) do nothing;

insert into assessment_component_scores (assessment_score_id, component_id, raw_value)
select s.id,
  (select id from assessment_components where phase_id = (select id from assessment_phases where name = '③ Umbrella Problem') and name = 'Assessment Score'),
  v.val
from assessment_scores s
join participants p on p.id = s.participant_id
join (values
    ('Thiviya', 5.0),
    ('Jishaka', 4.21),
    ('Piraveen', 4.926),
    ('Tamilini', 3.377),
    ('Abarna', 3.667),
    ('Kopina', 4.204),
    ('Hanoji', 4.148),
    ('Pirisa', 4.074),
    ('Kishalan', 3.42),
    ('Sabina', 4.204),
    ('Tharanginy', 4.0),
    ('Kamsayini', 3.87),
    ('Sharony', 2.988),
    ('Alansiya', 3.852),
    ('Jude Vinistan', 2.673),
    ('Banusha', 3.639),
    ('Kathirshan', 3.741),
    ('Parustana', 3.37),
    ('Kishani', 3.531),
    ('Prashayini', 3.352),
    ('Anojini', 3.287),
    ('Thanushiyan', 3.685),
    ('Koshalya', 3.13),
    ('Putanthahi', 3.491),
    ('Karthikan', 3.63),
    ('Sukanja', 3.444),
    ('Niruthigan', 3.333),
    ('Sathana', 3.481),
    ('Thadsayini', 3.352),
    ('Kalaikshana', 3.006),
    ('Nilakshana', 3.299),
    ('Ann Mareena', 3.386),
    ('Acksaya', 3.343),
    ('Raksayana', 3.056),
    ('Sahana', 3.463),
    ('Sathurshan', 3.0),
    ('Nishany', 3.093),
    ('Mathusha.P', 2.87),
    ('Mathusika', 2.679),
    ('Juliya Joy', 2.966),
    ('Thilakshan', 2.654),
    ('Sujanki', 3.441),
    ('Sivaruban', 3.056),
    ('Pirasanna', 2.593),
    ('Akshayan', 2.63),
    ('Lapishanth', 2.704)
) as v(pname, val) on v.pname = p.full_name
where s.phase_id = (select id from assessment_phases where name = '③ Umbrella Problem')
on conflict (assessment_score_id, component_id) do nothing;

insert into assessment_component_scores (assessment_score_id, component_id, raw_value)
select s.id,
  (select id from assessment_components where phase_id = (select id from assessment_phases where name = '④ Phase 2') and name = 'Fluency'),
  v.val
from assessment_scores s
join participants p on p.id = s.participant_id
join (values
    ('Abarna', 3.2),
    ('Acksaya', 4.4),
    ('Ann Mareena', 3.8),
    ('Anojini', 4.2),
    ('Banusha', 5.1),
    ('Jishaka', 3.8),
    ('Jude Vinistan', 3.3),
    ('Juliya Joy', 3.8),
    ('Kalaikshana', 2.5),
    ('Kamsayini', 2.9),
    ('Karthikan', 2.7),
    ('Kathirshan', 2.7),
    ('Kishalan', 4.3),
    ('Kishani', 4.1),
    ('Kopina', 4.0),
    ('Koshalya', 3.9),
    ('Lapishanth', 3.0),
    ('Mathusha.P', 1.9),
    ('Mathusika', 5.0),
    ('Nilakshana', 4.3),
    ('Niruthigan', 4.8),
    ('Nishany', 3.6),
    ('Parustana', 3.4),
    ('Pirasanna', 2.5),
    ('Piraveen', 4.5),
    ('Pirisa', 2.6),
    ('Prashayini', 3.9),
    ('Putanthahi', 4.5),
    ('Raksayana', 2.5),
    ('Sabina', 2.3),
    ('Sahana', 3.6),
    ('Sathana', 3.5),
    ('Sathurshan', 2.4),
    ('Sharony', 4.1),
    ('Sivaruban', 3.3),
    ('Sujanki', 4.2),
    ('Sukanja', 3.1),
    ('Thadsayini', 3.3),
    ('Tamilini', 3.1),
    ('Thanushiyan', 2.8),
    ('Tharanginy', 5.6),
    ('Thilakshan', 2.6),
    ('Thiviya', 5.5)
) as v(pname, val) on v.pname = p.full_name
where s.phase_id = (select id from assessment_phases where name = '④ Phase 2')
on conflict (assessment_score_id, component_id) do nothing;

insert into assessment_component_scores (assessment_score_id, component_id, raw_value)
select s.id,
  (select id from assessment_components where phase_id = (select id from assessment_phases where name = '④ Phase 2') and name = 'Confidence'),
  v.val
from assessment_scores s
join participants p on p.id = s.participant_id
join (values
    ('Abarna', 3.0),
    ('Acksaya', 6.0),
    ('Ann Mareena', 4.0),
    ('Anojini', 6.0),
    ('Banusha', 5.0),
    ('Jishaka', 5.0),
    ('Jude Vinistan', 4.0),
    ('Juliya Joy', 5.0),
    ('Kalaikshana', 3.0),
    ('Kamsayini', 3.0),
    ('Karthikan', 4.0),
    ('Kathirshan', 4.0),
    ('Kishalan', 3.0),
    ('Kishani', 5.0),
    ('Kopina', 5.0),
    ('Koshalya', 5.0),
    ('Lapishanth', 4.0),
    ('Mathusha.P', 2.0),
    ('Mathusika', 5.0),
    ('Nilakshana', 3.0),
    ('Niruthigan', 4.0),
    ('Nishany', 4.0),
    ('Parustana', 5.0),
    ('Pirasanna', 4.0),
    ('Piraveen', 5.0),
    ('Pirisa', 2.0),
    ('Prashayini', 5.0),
    ('Putanthahi', 4.0),
    ('Raksayana', 3.0),
    ('Sabina', 5.0),
    ('Sahana', 4.0),
    ('Sathana', 5.0),
    ('Sathurshan', 3.0),
    ('Sharony', 5.0),
    ('Sivaruban', 5.0),
    ('Sujanki', 6.0),
    ('Sukanja', 3.0),
    ('Thadsayini', 3.0),
    ('Tamilini', 5.0),
    ('Thanushiyan', 3.0),
    ('Tharanginy', 6.0),
    ('Thilakshan', 2.0),
    ('Thiviya', 6.0)
) as v(pname, val) on v.pname = p.full_name
where s.phase_id = (select id from assessment_phases where name = '④ Phase 2')
on conflict (assessment_score_id, component_id) do nothing;
