-- Historical Flag Carriers roster + status-update round for the Class of
-- 2025 cohort, from Class_of_2025_1.xlsx (Overview + Status - September 2026).

insert into flag_carriers (full_name, cohort_year, nic, date_of_birth, gender, mobile, email, address) values
  ('Aadarshan Chelliah Sivapathasundaram Sriskandan', '2025', '200534001517', '2005-12-05', 'Male', '0771127366', 'aadarshan55@gmail.com', '262/01, Ave Maria road, Colombuthurai, Jaffna'),
  ('Abishaliny Santhirapalan', '2025', null, null, 'Female', '0773415842', 'abishalinystff@gmail.com', 'No 235, vivekanantha nagar kilinochchi'),
  ('Abishana Varatharajan', '2025', '200475702296', '2004-09-13', 'Female', '0776348115', 'abishanavaratharajan@gmail.com', 'Kulapaadi road,
Kokuvil,
Jaffna'),
  ('Anosha Santhiravarnan', '2025', '200769301181', '2007-07-11', 'Female', '0764962874', 'dayanasanthiran@gmail.cooom', 'No:05 Alady Road, Thonikal,Vavuniya'),
  ('Catharin Sayanu Anton Joseph', '2025', '200071102616', '2000-07-29', 'Female', '0766261812', 'catharin0002@gmail.com', '979/10, Valanpuram Colomputhu Jaffna.'),
  ('Daksika Kugathas', '2025', '200566300533', '2005-06-11', 'Female', '0779410369', 'daksiktff@gmail.com', 'Market lane,Uduppiddy'),
  ('Daniyal Sathiyaseelan', '2025', '20053050378', '2005-10-31', 'Male', '0775019754', 'sathiyaseelandaniyal@gmail.com', 'No 7 2nd Cross Street Gurunagar jaffna'),
  ('Denita Nagarathinam', '2025', '200572600853', '2005-08-13', 'Female', '0761186129', 'denitanagarathinam@gmail.com', 'Mullaithevu'),
  ('Difna Ananthanayagam', '2025', '20056900263', '2005-07-08', 'Female', '0766683223', 'ananthanayagamdifna@gmail.com', '38, 2nd cross street gurunagar'),
  ('Dilakshana Kajandran', '2025', '200684500697', '2006-12-10', 'Female', '0741197112', 'vaishnavivaish5089931@gmail.com', '14/2 Rasavin thottam Jaffna.22'),
  ('Ishara Thilrukshi Devalagama Arachchige Senawirathna', '2025', '199876203462V', '1998-09-18', 'Female', '0766295539', 'isharathilrukshi98@gmail.com', 'Pallimunai west, Mannar'),
  ('Jericksha Wesley Judeson Divera', '2025', '200478700327', '2004-10-13', 'Female', '0777241885', 'jerickshadivera@gmail.com', '54, Rajendra road, Jaffna.'),
  ('John Kayas', '2025', '200518501132', '2005-07-03', 'Male', '0776199257', 'johngiresiyanjtff@gmail.com', 'No:-01, central east road, gurunagar, Jaffna'),
  ('Kabishan Manimaran', '2025', '200520600597', '2005-07-24', 'Male', '0779836142', 'kabishanmtff@gmail.com', 'Kalasali Road thriunelvely'),
  ('Kesayan Nanthakumar', '2025', '200434200325', '2005-12-07', 'Male', '0763370712', 'kesayanntff@gmail.com', 'Uduvil East,Chunnakam'),
  ('Kevin Derikshan Sahaya Jehan', '2025', '200601803126', '2006-01-18', 'Male', '0 76 962 9119', 'daksiktff@gmail.com', '184 Kacheri Nallur road, Jaffna'),
  ('Kirithiga Thavarasa', '2025', '200565000222', '2005-05-29', 'Female', '0776782960', 'kirithigathavarasa@gmail.com', '17/1,4th cross street columbuthurai Jaffna'),
  ('Kishani Ravinthirakumar', '2025', '200669603387', '2006-07-14', 'Female', '0702981153', 'kishanikishani332@gmail.com', 'Mannar.'),
  ('Kruthikan Vasathanayagam Josepious', '2025', '200512200272', '2005-05-01', 'Male', '0752310914', 'kruthikanvjtff@gmail.com', 'Kandy Road Kaithady South Kaithady'),
  ('Leesiya Suvarnan', '2025', null, '2005-02-02', 'Female', '0779768970', 'leesiyasuvarnan@gmail.com', 'Urunbiraj south dippo'),
  ('Majuran Selvarasa', '2025', '20032140033', '2003-08-01', 'Male', '0763578616', 'majuranmaju0801@gmail.com', '24, kadayitsuvami lane, neeraviyadi, jaffna'),
  ('Mary Rakshana Antony', '2025', '977521840V', '1997-09-08', 'Female', '0740130614', 'rakshanaatff@gmail.com', 'No.83, 3rd cross street, Maniyanthodam, Jaffna'),
  ('Mary Shiromy Thomas Edison', '2025', '20057590039', '2005-09-15', 'Female', '0776210220', 'shiromythomas@gmail.com', '205, Thornton Road, Thornton Heath, London
CR7 6BH'),
  ('Mathusan Jeevaranjan', '2025', '20021310123', '2002-05-10', 'Male', '0712920245', 'jeevamathusan@gmail.com', '46 keniyady lane ariyalai jaffna'),
  ('Meenuya Saththiyaseelan', '2025', '200561102052', '2005-04-20', 'Female', '076 47 62 946', 'meenuyastff@gmail.com', 'Navatkuli East Thachchanthopu, Kaithady.'),
  ('Nalajini Palasuparamaniyam', '2025', '200562602224', '2005-05-05', 'Female', '0779939406', 'balasubramaniyamnalajini@gmail.com', 'No 476 new scheme navatkuli west navatkuli'),
  ('Napitha Kirushnarasa', '2025', '200564501701', '2005-05-24', 'Female', '0762335456', null, '5 housing scheme Navatkuli junction kaithady'),
  ('Niroy Vincent Burton', '2025', '200508900517', '2005-03-29', 'Male', '0757122684', 'gangsterniroy@gmail.com', 'No 20, Martin Lane Jaffna'),
  ('Noel Richwini Fernando', '2025', '20045611217', '2004-03-01', 'Female', '0767356227', 'richwinifernando@gmail.com', 'Wa. No 7, pesalai ,Mannar'),
  ('Prashanth Regan', '2025', '200519200355', '2005-07-10', 'Male', '0760173394', 'prashanthregan10@gmail.com', '100/16 valanpuram colombuthurai'),
  ('Rachel Jemimah Enes Janzson', '2025', '200560900237', '2005-04-18', 'Female', '0753922153', 'rjemimah88@gmail.com', 'Palay Road Urumpirai south Urumpirai'),
  ('Sampavi Sivanantham', '2025', '200270000253', '2002-07-18', 'Female', '0778691587', 'sampavisiva18@gmail.com', '46,Natharies Lane,Ariyalai, Jaffna'),
  ('Sanushika Kajenthirakumar', '2025', '200274602141', '2002-09-02', 'Female', '0764119886', 'jasojasothini80@gmail.com', 'Velanai east 3rd ward, Velanai.'),
  ('Sathurshana Paskaran', '2025', '978201385V', '1997-11-15', 'Female', '0769922474', 'sathurshanaptff@gmail.com', 'Hospital Road, Tellippalai'),
  ('Senthury Vasinthiran', '2025', '2007677201438', '2007-06-20', 'Female', '0775201232', null, 'Sayamboo veethi,Karainakar.'),
  ('Sharon Raveendran', '2025', '20041380031', '2004-05-17', 'Male', '0761825886', 'daksiktff@gmail.com', '1/5 1st lane chundukuli eachamoddai road The apostolic church'),
  ('Thamilarasi Kasinkumar', '2025', '200385000371', '2003-12-14', 'Female', '0764653092', 'mithuthamilarasi5@gmail.com', 'Kalviyankadu, nallur, Jaffna'),
  ('Theepiga Parameswaran', '2025', '200585300404', '2005-12-18', 'Female', '0702151483', 'theepigaptff@gmail.com', 'Velanai 4 th ward velanai'),
  ('Thipika Satheeswaran', '2025', '200576100552', '2005-09-17', 'Female', '0772342089', 'thibikastff@gmail.com', 'Kaithady South kaithady'),
  ('Thiponigaa Jeyathas', '2025', '200568200251', '2005-06-30', 'Female', '0743203065', 'thiponigaa03@gmail.com', 'No 20 , 2/2 blue hills residencies, dehiwala, Colombo'),
  ('Thulasika Navaraththinam', '2025', '2001683003', '2001-07-01', 'Female', '0753295462', 'thulasikantff@gmail.com', 'Urumpirai north Urumpirai'),
  ('Tishanthy Sivananthan', '2025', '200465200071', '2004-05-31', 'Female', '0743634981', 'tishanthystff@gmail.com', '162,uddupiddy road, vathiry,jaraveddy.'),
  ('Venujan Balachandran', '2025', '20050770172', '2005-03-17', 'Male', '0768440653', 'balavenu17@gmail.com', 'Jaffna'),
  ('Vithuja Thevaseelan', '2025', '200486000323', '2004-12-25', 'Female', '0768599738', 'vithujattff@gmail.com', 'Sanguvely North manipay');

-- Round: September 2026
insert into flag_carrier_updates (flag_carrier_id, round_label, round_date, studying, study_mode, program_course, institution, working, work_mode, job_role, employer, areas_of_interest, notes, follow_up)
select fc.id, 'September 2026', '2026-09-01',
  v.studying, v.study_mode, v.program_course, v.institution, v.working, v.work_mode, v.job_role, v.employer, v.areas_of_interest, v.notes, v.follow_up
from flag_carriers fc
join (values
    ('Aadarshan Chelliah Sivapathasundaram Sriskandan', true, 'Full-time', 'Business Administration', 'University of Jaffna', true, 'Part-time', 'Teaching assistant', 'British council , Jaffna', 'Business/Entrepreneurship, Education/Teaching, Hospitality/Tourism', 'I have started working as a freelancer in document translations and copy typing', false),
    ('Abishaliny Santhirapalan', false, null, null, null, true, 'Full-time', 'Accountant', 'Do Bosco school of excellence , St Theresa college lane karadippokku kilinochchi', 'Finance/Banking', 'After completing TFF, Suba and Abirami recommended me for this job.  I joined this organization, and it has now been seven months since I started working here.

Thank you for giving me this opportunity.', false),
    ('Abishana Varatharajan', true, 'Full-time', 'ICT', 'VTA', false, null, null, null, 'Education/Teaching, Law', 'Studying', false),
    ('Anosha Santhiravarnan', true, 'Part-time', null, null, true, 'Part-time', null, null, null, 'Studying part-time and managing clothing business.', true),
    ('Catharin Sayanu Anton Joseph', true, 'Part-time', 'Bible College', 'College Of Theology', true, 'Part-time', 'field officer.  volunteer.', 'SOND , Jaffna', 'Other', 'No.', false),
    ('Daksika Kugathas', false, null, null, null, true, 'Full-time', 'Facilitator Support', 'The Flags Forum, Srilanka', 'Finance/Banking, Business/Entrepreneurship, Education/Teaching, Hospitality/Tourism', 'I applied for degree course in Hotel & Tourism management and also applied marketing in business management course in open university .', false),
    ('Daniyal Sathiyaseelan', false, null, null, null, true, 'Full-time', 'Farmer and fishermen', 'Sea cucumber farm , Sea', 'Marine, Other', 'No', false),
    ('Denita Nagarathinam', false, null, null, null, true, 'Full-time', null, null, null, 'Working at bookshop in Mullaitivu', true),
    ('Difna Ananthanayagam', true, 'Full-time', 'HNDA course', 'Advance level technical college', false, null, null, null, 'Finance/Banking, Business/Entrepreneurship', 'No', false),
    ('Dilakshana Kajandran', false, null, null, null, false, null, null, null, null, null, true),
    ('Ishara Thilrukshi Devalagama Arachchige Senawirathna', false, null, null, null, false, null, null, null, 'Social Science, Law', 'Currently, I’m unemployed and looking for a job in my field of interest. Unfortunately, I haven’t get a job in my interest field, so I’ve decided to do any suitable job for me ,as well as  I’m preparing for government job examinations.', false),
    ('Jericksha Wesley Judeson Divera', false, null, null, null, true, 'Full-time', 'Facilitator support', 'The Flag Forum, Jaffna', 'Business/Entrepreneurship, Healthcare/Medicine, Arts/Design/Media', 'Currently I am a facilitator support at The Flag Forum and in my free time I am giving personal class', false),
    ('John Kayas', true, 'Full-time', 'Bachelor''s in arts', 'University of Jaffna', true, 'Part-time', 'Fishing', 'Relatives own work, Jaffna', 'Education/Teaching', 'I''m currently studying and working as a fisherman', false),
    ('Kabishan Manimaran', true, 'Full-time', 'Advance level', '.', false, null, null, null, 'Finance/Banking, Business/Entrepreneurship', 'Sports', false),
    ('Kesayan Nanthakumar', true, 'Full-time', 'Civil Engibeering', 'University of Peradeniya', false, null, null, null, 'Engineering, Finance/Banking, Education/Teaching, Hospitality/Tourism, Other', 'Currently at the end of my first year in the university. Joined book club where people share thoughts, a film review comitee where we critically review movies that has very good plot line and cinematography , also took part in debate tournament in which our team progressed untim the semi final', false),
    ('Kevin Derikshan Sahaya Jehan', false, null, null, null, false, null, null, null, 'Other', 'Looking for a job and I have a plan to continue my studies', false),
    ('Kirithiga Thavarasa', true, 'Full-time', 'Arts', 'University of Jaffna', false, null, null, null, 'Finance/Banking, Education/Teaching', 'I''m going to study university of Jaffna,now only orientation is finish.it will start soon', false),
    ('Kishani Ravinthirakumar', false, null, null, null, false, null, null, null, null, null, false),
    ('Kruthikan Vasathanayagam Josepious', true, 'Full-time', 'Automobile engineering', 'Jeraman tech', false, null, null, null, 'Engineering', 'Nothing', false),
    ('Leesiya Suvarnan', true, 'Part-time', 'Piraimary education degree', 'Kilinoshsi', false, null, null, null, 'Education/Teaching', 'Nothing', false),
    ('Majuran Selvarasa', false, null, null, null, true, 'Full-time', 'Mobile shop', 'M. Mobile shop , Jaffna', 'Business/Entrepreneurship, Education/Teaching, Healthcare/Medicine, Hospitality/Tourism, Arts/Design/Media', 'No', false),
    ('Mary Rakshana Antony', false, null, null, null, true, 'Full-time', 'Data collector', 'Gate Institute , Jaffna', 'Healthcare/Medicine, Hospitality/Tourism', 'It is difficult to commit to a job due to family needs. I’d like to continue nursing but I also want to help my husband and family. I also have a very active family that likes to participate in religious and leisure and I find it difficult to say no sometimes.', false),
    ('Mary Shiromy Thomas Edison', true, 'Full-time', 'BA Business Management', 'University of Greenwich', true, 'Part-time', 'Cashier', 'Iam working as a employee in Convenience store , London', 'Business/Entrepreneurship, Education/Teaching, Arts/Design/Media', 'Iam an international student who is studying Bachelors in England and after I finished my higher studies I will come back to Sri Lanka.', false),
    ('Mathusan Jeevaranjan', false, null, null, null, false, null, null, null, 'Engineering, IT/Software, Finance/Banking, Business/Entrepreneurship, Arts/Design/Media, Other', 'I have searching for job vacancies in my social media', false),
    ('Meenuya Saththiyaseelan', true, 'Full-time', 'Bachelor Of Commerce (BCom).', 'University', false, null, null, null, 'IT/Software, Finance/Banking, Business/Entrepreneurship, Law', 'I''m studying at University BCom degree because of I''m interesting in banking sector accounting.', false),
    ('Nalajini Palasuparamaniyam', true, 'Full-time', 'Bachelor of commerce', 'University of Jaffna', false, null, null, null, 'Finance/Banking, Business/Entrepreneurship, Education/Teaching, Arts/Design/Media', 'Nothing but I need to part time job', false),
    ('Napitha Kirushnarasa', false, null, null, null, false, null, null, null, 'Education/Teaching', 'When does my work as a preschool teacher finish.', false),
    ('Niroy Vincent Burton', false, null, null, null, true, 'Full-time', 'Trainee Staff Assistant', 'Sampath Bank PLC, Jaffna', 'IT/Software, Finance/Banking, Healthcare/Medicine', '.', false),
    ('Noel Richwini Fernando', true, 'Full-time', 'Veterinary medicine degree', 'University of Peradeniya', false, null, null, null, 'Education/Teaching, Healthcare/Medicine, Arts/Design/Media', 'No', false),
    ('Prashanth Regan', false, null, null, null, true, 'Part-time', 'Teaching assistant', 'British Council , Jaffna', 'Engineering, Marine, Law, Other', 'Waiting for HND admission', false),
    ('Rachel Jemimah Enes Janzson', false, null, null, null, false, null, null, null, 'Finance/Banking', 'Nothing', false),
    ('Sampavi Sivanantham', false, null, null, null, true, 'Full-time', null, null, null, 'Work as a photographer for the video production company ''Saho Creation,'' and also serve as a manager, graphic designer, and video editor at ''Saho Creative Academy.''', true),
    ('Sanushika Kajenthirakumar', false, null, null, null, false, null, null, null, null, null, true),
    ('Sathurshana Paskaran', false, null, null, null, true, 'Full-time', 'Typist', 'Vavuniya Courts , Vavuniya', 'IT/Software, Arts/Design/Media', 'I am currently doing a job I enjoy. What I learned at TFF has been helpful in doing this work.', false),
    ('Senthury Vasinthiran', false, null, null, null, true, 'Full-time', null, null, null, 'Working at a textile shop', true),
    ('Sharon Raveendran', false, null, null, null, false, null, null, null, 'IT/Software, Business/Entrepreneurship, Arts/Design/Media', 'Studying German language', false),
    ('Thamilarasi Kasinkumar', true, 'Full-time', 'HND IT', 'SriLanka Institute Of Advanced Technological Education In Jaffna', false, null, null, null, 'IT/Software, Finance/Banking, Education/Teaching', 'No', false),
    ('Theepiga Parameswaran', true, 'Full-time', 'BA', 'Open university of Jaffna', false, null, null, null, 'Business/Entrepreneurship, Social Science', 'Nope', false),
    ('Thipika Satheeswaran', false, null, null, null, false, null, null, null, 'Education/Teaching', 'No', false),
    ('Thiponigaa Jeyathas', true, 'Full-time', 'AI & Robotics (higher Diploma)', 'SCU (Sliit city uni ) (kolpitiya)', false, null, null, null, 'IT/Software, Education/Teaching, Other', 'I am studying now but I need a part time work like work from home , I have classes only for weekdays so I expect a work from home in weekends . Now I am searching those kind a jobs 
Thank you', false),
    ('Thulasika Navaraththinam', true, 'Part-time', 'BA degree programme....', 'The open university jaffna', true, 'Full-time', 'Accountant', 'Maniyam stores kondavil...., Jaffna kondavil', 'Education/Teaching', 'I am currently doing degree  in Bachelor of arts and also doing part time work as a accountant.', false),
    ('Tishanthy Sivananthan', true, 'Full-time', 'Architecture', 'General Sir John Kotelawa Defence University', false, null, null, null, 'Business/Entrepreneurship, Education/Teaching, Arts/Design/Media', 'Nope', false),
    ('Venujan Balachandran', true, 'Full-time', 'AI and Robotics', 'SCU', false, null, null, null, 'IT/Software', 'Studying', false),
    ('Vithuja Thevaseelan', true, 'Full-time', 'University', 'University of jaffna', false, null, null, null, 'Education/Teaching, Social Science, Healthcare/Medicine, Hospitality/Tourism, Agriculture', 'Nill', false)
) as v(full_name, studying, study_mode, program_course, institution, working, work_mode, job_role, employer, areas_of_interest, notes, follow_up) on v.full_name = fc.full_name
where fc.cohort_year = '2025'
on conflict (flag_carrier_id, round_label) do nothing;